packages: []
catalogs:
  build:
    tsdown: ^0.20.3
  dev:
    '@vscode/vsce': ^3.7.1
    bumpp: ^10.4.1
    pncat: ^0.10.2
    reactive-vscode: ^0.4.1
    simple-git-hooks: ^2.13.1
    taze: ^19.9.2
    typescript: ^5.9.3
    vscode-ext-gen: ^1.6.0
    vsxpub: ^0.1.3
  lint:
    '@octohash/eslint-config': ^0.2.3
    eslint: ^10.0.0
    lint-staged: ^16.2.7
  test:
    vitest: ^4.0.18
  types:
    '@types/node': ^25.3.0
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - '@vscode/vsce-sign'
  - keytar
